use crate::Scalar;
use crate::model::ContinuousModel;
use crate::scalar::{from_f64, from_usize};

/// Normalized Butterworth cascade.
///
/// Odd orders begin with one real pole. The remaining states are pairs
/// `[section_output, normalized_output_derivative]` for real biquads. Biquads
/// are ordered from lowest Q to highest Q to reduce internal peaking.
#[derive(Clone, Copy, Debug)]
pub(crate) struct Butterworth<T, const N: usize> {
    damping: [T; N],
}

impl<T: Scalar, const N: usize> Butterworth<T, N> {
    pub(crate) fn new() -> Self {
        let mut damping = [T::zero(); N];
        let section_count = N / 2;
        let denominator = from_f64::<T>(2.0) * from_usize::<T>(N);

        for (index, coefficient) in damping.iter_mut().take(section_count).enumerate() {
            let odd_number = from_usize::<T>(2 * index + 1);
            *coefficient = from_f64::<T>(2.0) * (T::PI() * odd_number / denominator).sin();
        }

        // Lower-Q sections have greater damping. Put them first so they reduce
        // the signal before it reaches sections with resonant internal gain.
        for index in 1..section_count {
            let mut position = index;
            while position > 0 && damping[position - 1] < damping[position] {
                damping.swap(position - 1, position);
                position -= 1;
            }
        }

        Self { damping }
    }

    #[cfg(test)]
    pub(crate) fn damping(&self) -> &[T] {
        &self.damping[..N / 2]
    }
}

impl<T: Scalar, const N: usize> ContinuousModel<T, N> for Butterworth<T, N> {
    fn derivative(&self, state: &[T; N], input: T, derivative: &mut [T; N]) {
        let mut driving_signal = input;
        let mut state_index = 0;

        if N % 2 == 1 {
            derivative[0] = driving_signal - state[0];
            driving_signal = state[0];
            state_index = 1;
        }

        let mut section_index = 0;
        while state_index + 1 < N {
            let output = state[state_index];
            let output_derivative = state[state_index + 1];
            derivative[state_index] = output_derivative;
            derivative[state_index + 1] =
                driving_signal - output - self.damping[section_index] * output_derivative;
            driving_signal = output;
            state_index += 2;
            section_index += 1;
        }
    }

    fn output(&self, state: &[T; N], _input: T) -> T {
        if N == 1 { state[0] } else { state[N - 2] }
    }

    fn equilibrium(&self, input: T) -> [T; N] {
        let mut state = [T::zero(); N];
        let mut state_index = 0;
        if N % 2 == 1 {
            state[0] = input;
            state_index = 1;
        }
        while state_index + 1 < N {
            state[state_index] = input;
            state_index += 2;
        }
        state
    }

    fn max_normalized_step(&self) -> T {
        // Every normalized Butterworth pole has unit magnitude. Keeping the
        // step below one is conservative for Dormand-Prince and lightly damped
        // sections alike.
        T::one()
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::cast_precision_loss, clippy::float_cmp)]

    use approx::assert_relative_eq;

    use super::*;

    #[test]
    fn fourth_order_coefficients_match_known_factors() {
        let model = Butterworth::<f64, 4>::new();
        assert_relative_eq!(model.damping()[0], 1.847_759_065_022_573_5, epsilon = 1e-15);
        assert_relative_eq!(model.damping()[1], 0.765_366_864_730_179_6, epsilon = 1e-15);
    }

    #[test]
    fn cascade_matches_closed_form_magnitude() {
        for order in 1..=16 {
            check_magnitude::<f64>(order, 0.1);
            check_magnitude::<f64>(order, 1.0);
            check_magnitude::<f64>(order, 3.0);
        }
    }

    fn check_magnitude<T: Scalar>(order: usize, frequency: T) {
        // This helper checks coefficients generated by the same closed formula
        // used by any const-generic order without requiring runtime-sized state.
        let pair_count = order / 2;
        let mut actual = T::one();
        if order % 2 == 1 {
            actual = T::one() / (T::one() + frequency * frequency).sqrt();
        }
        for index in 0..pair_count {
            let angle = T::PI() * from_usize::<T>(2 * index + 1)
                / (from_f64::<T>(2.0) * from_usize::<T>(order));
            let damping = from_f64::<T>(2.0) * angle.sin();
            let real = T::one() - frequency * frequency;
            let imaginary = damping * frequency;
            actual = actual / (real * real + imaginary * imaginary).sqrt();
        }
        let expected = T::one() / (T::one() + frequency.powf(from_usize::<T>(2 * order))).sqrt();
        assert!((actual - expected).abs() <= from_f64(2.0e-13));
    }

    #[test]
    fn equilibrium_has_zero_derivative_for_odd_and_even_orders() {
        check_equilibrium::<3>();
        check_equilibrium::<4>();
    }

    fn check_equilibrium<const ORDER: usize>() {
        let model = Butterworth::<f64, ORDER>::new();
        let state = model.equilibrium(2.5);
        let mut derivative = [1.0; ORDER];
        model.derivative(&state, 2.5, &mut derivative);
        assert!(derivative.iter().all(|value| *value == 0.0));
        assert_eq!(model.output(&state, 2.5), 2.5);
    }
}
