#!/usr/bin/env python3
"""Generate the magnitude-normalized Bessel prototype table.

This is a development helper, not a build dependency. It requires SciPy and
writes Rust source to stdout:

    python3 scripts/generate_bessel_table.py > src/model/bessel_table.rs
"""

from math import hypot

from scipy.signal import besselap


MAX_ORDER = 25


def rust_array(name: str, values: list[float | int], rust_type: str) -> None:
    print(f"pub(crate) const {name}: [{rust_type}; {len(values)}] = [")
    for start in range(0, len(values), 4):
        row = values[start : start + 4]
        if rust_type == "f64":
            rendered = ", ".join(f"{value:.17e}" for value in row)
        else:
            rendered = ", ".join(str(value) for value in row)
        print(f"    {rendered},")
    print("];")
    print()


def main() -> None:
    offsets = [0]
    real_rates: list[float] = []
    damping: list[float] = []
    frequency_squared: list[float] = []

    for order in range(1, MAX_ORDER + 1):
        _, poles, _ = besselap(order, norm="mag")
        real_poles = [pole for pole in poles if abs(pole.imag) < 1.0e-12]
        real_rates.append(-real_poles[0].real if real_poles else 0.0)

        sections = [
            (-2.0 * pole.real, hypot(pole.real, pole.imag) ** 2)
            for pole in poles
            if pole.imag > 1.0e-12
        ]
        # Low-Q sections first reduces the signal reaching resonant sections.
        sections.sort(key=lambda section: section[0] / section[1] ** 0.5, reverse=True)
        damping.extend(section[0] for section in sections)
        frequency_squared.extend(section[1] for section in sections)
        offsets.append(len(damping))

    print("// Generated by scripts/generate_bessel_table.py; do not edit by hand.")
    print("// Reference: scipy.signal.besselap(order, norm=\"mag\"), orders 1..=25.")
    print("#![allow(clippy::excessive_precision, clippy::unreadable_literal)]")
    print()
    print(f"pub(crate) const MAX_ORDER: usize = {MAX_ORDER};")
    print()
    print("pub(crate) struct Prototype {")
    print("    pub(crate) real_rate: f64,")
    print("    pub(crate) damping: &'static [f64],")
    print("    pub(crate) frequency_squared: &'static [f64],")
    print("}")
    print()
    print("pub(crate) fn prototype(order: usize) -> Option<Prototype> {")
    print("    if order == 0 || order > MAX_ORDER {")
    print("        return None;")
    print("    }")
    print("    let start = SECTION_OFFSETS[order - 1];")
    print("    let end = SECTION_OFFSETS[order];")
    print("    Some(Prototype {")
    print("        real_rate: REAL_RATES[order - 1],")
    print("        damping: &DAMPING[start..end],")
    print("        frequency_squared: &FREQUENCY_SQUARED[start..end],")
    print("    })")
    print("}")
    print()
    rust_array("SECTION_OFFSETS", offsets, "usize")
    rust_array("REAL_RATES", real_rates, "f64")
    rust_array("DAMPING", damping, "f64")
    rust_array("FREQUENCY_SQUARED", frequency_squared, "f64")


if __name__ == "__main__":
    main()
